trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- script: dotnet restore
  displayName: Ripristina i pacchetti NuGet

- script: |
     cd AcademyA.LegoCatalog.API
     dotnet build --configuration $(buildConfiguration)
  displayName: Compilazione del progetto API